/*
const ADD_MESSAGE = "ADD_MESSAGE";
const ADD_MESSAGE_NAME     = "ADD_MESSAGE_NAME";
const ADD_MESSAGE_QUESTION = "ADD_MESSAGE_QUESTION";
const ADD_MESSAGE_ANSWER = "ADD_MESSAGE_ANSWER";
const ADD_ITEM = "ADD_ITEM";
const SELECT_ITEM = "SELECT ITEM";
const SET_MESSAGE = "SET MESSAGE";
const SET_MEDIA_CONTROL_TYPE = "SET MEDIA CONTROL TYPE";
const ADD_MESSAGE_VIDEO = "ADD MESSAGE VIDEO";
const SET_MEDIA_CONTROL_STATE = "SET MEDIA CONTROL STATE";
const SET_MEDIA_VIDEO = "SET MEDIA VIDEO";
const ADD_RECEPIENT_FIRSTNAME = "ADD_RECEPIENT_FIRSTNAME";
const ADD_RECEPIENT_LASTNAME = "ADD_RECEPIENT_LASTNAME";
const ADD_RECEPIENT_EMAIL = "ADD_RECEPIENT_EMAIL";
const ADD_RECEPIENT_MOBILE = "ADD_RECEPIENT_MOBILE";
const ADD_RECEPIENT_QUESTION = "ADD_RECEPIENT_QUESTION";
const ADD_RECEPIENT_ANSWER = "ADD_RECEPIENT_ANSWER";
const SET_RECEPIENT = "SET_RECEPIENT";
const SET_TRANSFER = "SET_TRANSFER";
const DO_TRANSFER = "DO_TRANSFER";
const SELECT_TRANSFER_SOURCE_ITEM = "SELECT_TRANSFER_SOURCE_ITEM";
const SET_MANAGER_CONTROL_TYPE = "SET_MANAGER_CONTROL_TYPE";
const SELECT_TRANSFER_TARGET_ITEM ="SELECT_TRANSFER_TARGET_ITEM";
const ADD_RECEPIENT_MESSAGE_LIST = "ADD_RECEPIENT_MESSAGE_LIST";
const ADD_EXECUTOR_FIRSTNAME = "ADD_EXECUTOR_FIRSTNAME";
const ADD_EXECUTOR_LASTNAME = "ADD_EXECUTOR_LASTNAME";
const ADD_EXECUTOR_EMAIL = "ADD_EXECUTOR_EMAIL";
const ADD_EXECUTOR_MOBILE = "ADD_EXECUTOR_MOBILE"; 
const ADD_EXECUTOR_RECEPIENT_LIST = "ADD_EXECUTOR_RECEPIENT_LIST";
const SET_EXECUTOR = "SET_EXECUTOR";
const NEW_MESSAGE = "NEW_MESSAGE";
const EDIT_ITEM   = "EDIT_ITEM"; 
const NEW_EXECUTOR = "NEW_EXECUTOR";
const NEW_RECEPIENT ="NEW_RECEPIENT";
const ADD_SIGNUP_FIRSTNAME = "ADD_SIGNUP_FIRSTNAME";
const ADD_SIGNUP_LASTNAME = "ADD_SIGNUP_LASTNAME"; 
const ADD_SIGNUP_EMAIL = "ADD_SIGNUP_EMAIL";
const ADD_SIGNUP_USERID ="ADD_SIGNUP_USERID";
const ADD_SIGNUP_PASSWORD = "ADD_SIGNUP_PASSWORD"; 
const ADD_SIGNUP_CONFIRM_PASSWORD ="ADD_SIGNUP_CONFIRM_PASSWORD";
const ADD_SIGNUP_BIRTHDAY = "ADD_SIGNUP_BIRTHDAY"; 
const ADD_SIGNUP = "ADD_SIGNUP";
const ADD_LOGIN_USERID = "ADD_LOGIN_USERID";
const ADD_LOGIN_PASSWORD = "ADD_LOGIN_PASSWORD";
const LOGIN_SIGNUP = "LOGIN_SIGNUP";
const CLEAR_STATUS_SIGNUP = "CLEAR_STATUS_SIGNUP";
const ADD_CONTACT_FIRSTNAME       = "ADD_CONTACT_FIRSTNAME";     
const ADD_CONTACT_LASTNAME        = "ADD_CONTACT_LASTNAME";      
const ADD_CONTACT_EMAIL           = "ADD_CONTACT_EMAIL";         
const ADD_CONTACT_EMAIL_MESSAGE   = "ADD_CONTACT_EMAIL_MESSAGE";
const ADD_CONTACT = "ADD_CONTACT";
const ADD_ITEMS = "ADD_ITEMS";
const ADD_SESSION_DATA ="ADD_SESSION_DATA";
const RESET_APP = "RESET_APP";
const SET_LOGIN_SIGNUP = "SET_LOGIN_SIGNUP";
const SET_ADD_SIGNUP = "SET_ADD_SIGNUP";*/
const ADD_INVENTORY_ITEMS = "ADD_INVENTORY_ITEMS";
const SET_CURRENT_ITEM_QUANTITY = "SET_CURRENT_ITEM_QUANTITY";
const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
const ADD_CURRENT_ITEM_TO_CART = "ADD_CURRENT_ITEM_TO_CART";
const SET_CART_ITEM_QUANTITY = "SET_CART_ITEM_QUANTITY";
const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
const CUSTOMER_CHECK_OUT = "CUSTOMER_CHECK_OUT";
const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
const SORT_CURRENT_CATEGORY_ITEMS ="SORT_CURRENT_CATEGORY_ITEMS";
const FILTER_CURRENT_CATEGORY_ITEMS = "FILTER_CURRENT_CATEGORY_ITEMS";
const UNFILTER_CURRENT_CATEGORY_ITEMS = "UNFILTER_CURRENT_CATEGORY_ITEMS";
const PAUSE_CAROUSEL = "PAUSE_CAROUSEL";
const PLAY_CAROUSEL = "PLAY_CAROUSEL";
const ADD_CURRENT_ITEM_QUANTITY = "ADD_CURRENT_ITEM_QUANTITY";
const SET_CAN_SHOW_CHECKOUT_MESSAGE ="SET_CAN_SHOW_CHECKOUT_MESSAGE";
const SET_CUSTOMER_NAME        = "SET_CUSTOMER_NAME";       
const SET_CUSTOMER_ADDRESS     = "SET_CUSTOMER_ADDRESS";     
const SET_CUSTOMER_CITY        = "SET_CUSTOMER_CITY";       
const SET_CUSTOMER_PHONENUMBER = "SET_CUSTOMER_PHONENUMBER";
const SET_CONTACT_NAME    = "SET_CONTACT_NAME"; 
const SET_CONTACT_EMAIL   = "SET_CONTACT_EMAIL";  
const SET_CONTACT_SUBJECT = "SET_CONTACT_SUBJECT";
const SET_CONTACT_MESSAGE = "SET_CONTACT_MESSAGE";
const SEND_CONTACT_INFORMATION = "SEND_CONTACT_INFORMATION";
const SET_CAN_SHOW_CONTACT_MESSAGE = "SET_CAN_SHOW_CONTACT_MESSAGE";

module.exports = {
    /* ADD_MESSAGE,
    ADD_MESSAGE_NAME,
    ADD_MESSAGE_QUESTION,
    ADD_MESSAGE_ANSWER,
    ADD_ITEM,
    SELECT_ITEM,
    SET_MESSAGE,
    SET_MEDIA_CONTROL_TYPE,
    ADD_MESSAGE_VIDEO,
    SET_MEDIA_CONTROL_STATE, 
    SET_MEDIA_VIDEO, 
    ADD_RECEPIENT_FIRSTNAME,
    ADD_RECEPIENT_LASTNAME,
    ADD_RECEPIENT_EMAIL,
    ADD_RECEPIENT_MOBILE,
    ADD_RECEPIENT_QUESTION,
    ADD_RECEPIENT_ANSWER,
    SET_RECEPIENT,
    SET_TRANSFER,
    DO_TRANSFER,
    SELECT_TRANSFER_SOURCE_ITEM,
    SET_MANAGER_CONTROL_TYPE,
    SELECT_TRANSFER_TARGET_ITEM,
    ADD_RECEPIENT_MESSAGE_LIST,
    ADD_EXECUTOR_FIRSTNAME,
    ADD_EXECUTOR_LASTNAME,
    ADD_EXECUTOR_EMAIL,
    ADD_EXECUTOR_MOBILE,
    ADD_EXECUTOR_RECEPIENT_LIST,
    SET_EXECUTOR,
    NEW_MESSAGE, 
    EDIT_ITEM,
    NEW_EXECUTOR, 
    NEW_RECEPIENT,
    ADD_SIGNUP_FIRSTNAME,
    ADD_SIGNUP_LASTNAME, 
    ADD_SIGNUP_EMAIL,
    ADD_SIGNUP_USERID,
    ADD_SIGNUP_PASSWORD, 
    ADD_SIGNUP_CONFIRM_PASSWORD,
    ADD_SIGNUP_BIRTHDAY, 
    ADD_SIGNUP,
    ADD_LOGIN_USERID,
    ADD_LOGIN_PASSWORD,
    LOGIN_SIGNUP,
    CLEAR_STATUS_SIGNUP,
    ADD_CONTACT_FIRSTNAME,    
    ADD_CONTACT_LASTNAME,     
    ADD_CONTACT_EMAIL,        
    ADD_CONTACT_EMAIL_MESSAGE,
    ADD_CONTACT,
    ADD_ITEMS,
    ADD_SESSION_DATA,
    RESET_APP,
    SET_LOGIN_SIGNUP,
    SET_ADD_SIGNUP,*/
    ADD_INVENTORY_ITEMS,
    SET_CURRENT_ITEM_QUANTITY,
    SET_CURRENT_ITEM,
    ADD_CURRENT_ITEM_TO_CART,
    SET_CART_ITEM_QUANTITY,
    REMOVE_CART_ITEM,
    CUSTOMER_CHECK_OUT,
    SET_CURRENT_CATEGORY,
    SORT_CURRENT_CATEGORY_ITEMS,
    FILTER_CURRENT_CATEGORY_ITEMS,
    UNFILTER_CURRENT_CATEGORY_ITEMS,
    PAUSE_CAROUSEL,
    PLAY_CAROUSEL,
    ADD_CURRENT_ITEM_QUANTITY,
    SET_CAN_SHOW_CHECKOUT_MESSAGE,
    SET_CUSTOMER_NAME,       
    SET_CUSTOMER_ADDRESS,    
    SET_CUSTOMER_CITY,       
    SET_CUSTOMER_PHONENUMBER,
    SET_CONTACT_NAME,   
    SET_CONTACT_EMAIL,  
    SET_CONTACT_SUBJECT,
    SET_CONTACT_MESSAGE,
    SEND_CONTACT_INFORMATION,
    SET_CAN_SHOW_CONTACT_MESSAGE,
};