const ADD_INVENTORY_ITEMS = "ADD_INVENTORY_ITEMS";
const SET_CURRENT_ITEM_QUANTITY = "SET_CURRENT_ITEM_QUANTITY";
const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
const ADD_CURRENT_ITEM_TO_CART = "ADD_CURRENT_ITEM_TO_CART";
const SET_CART_ITEM_QUANTITY = "SET_CART_ITEM_QUANTITY";
const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
const CUSTOMER_CHECK_OUT = "CUSTOMER_CHECK_OUT";
const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
const SORT_CURRENT_CATEGORY_ITEMS ="SORT_CURRENT_CATEGORY_ITEMS";
const FILTER_CURRENT_CATEGORY_ITEMS = "FILTER_CURRENT_CATEGORY_ITEMS";
const UNFILTER_CURRENT_CATEGORY_ITEMS = "UNFILTER_CURRENT_CATEGORY_ITEMS";
const PAUSE_CAROUSEL = "PAUSE_CAROUSEL";
const PLAY_CAROUSEL = "PLAY_CAROUSEL";
const ADD_CURRENT_ITEM_QUANTITY = "ADD_CURRENT_ITEM_QUANTITY";
const SET_CAN_SHOW_CHECKOUT_MESSAGE ="SET_CAN_SHOW_CHECKOUT_MESSAGE";
const SET_CUSTOMER_NAME        = "SET_CUSTOMER_NAME";       
const SET_CUSTOMER_ADDRESS     = "SET_CUSTOMER_ADDRESS";     
const SET_CUSTOMER_CITY        = "SET_CUSTOMER_CITY";       
const SET_CUSTOMER_PHONENUMBER = "SET_CUSTOMER_PHONENUMBER";
const SET_CONTACT_NAME    = "SET_CONTACT_NAME"; 
const SET_CONTACT_EMAIL   = "SET_CONTACT_EMAIL";  
const SET_CONTACT_SUBJECT = "SET_CONTACT_SUBJECT";
const SET_CONTACT_MESSAGE = "SET_CONTACT_MESSAGE";
const SEND_CONTACT_INFORMATION = "SEND_CONTACT_INFORMATION";
const SET_CAN_SHOW_CONTACT_MESSAGE = "SET_CAN_SHOW_CONTACT_MESSAGE";

module.exports = {
    ADD_INVENTORY_ITEMS,
    SET_CURRENT_ITEM_QUANTITY,
    SET_CURRENT_ITEM,
    ADD_CURRENT_ITEM_TO_CART,
    SET_CART_ITEM_QUANTITY,
    REMOVE_CART_ITEM,
    CUSTOMER_CHECK_OUT,
    SET_CURRENT_CATEGORY,
    SORT_CURRENT_CATEGORY_ITEMS,
    FILTER_CURRENT_CATEGORY_ITEMS,
    UNFILTER_CURRENT_CATEGORY_ITEMS,
    PAUSE_CAROUSEL,
    PLAY_CAROUSEL,
    ADD_CURRENT_ITEM_QUANTITY,
    SET_CAN_SHOW_CHECKOUT_MESSAGE,
    SET_CUSTOMER_NAME,       
    SET_CUSTOMER_ADDRESS,    
    SET_CUSTOMER_CITY,       
    SET_CUSTOMER_PHONENUMBER,
    SET_CONTACT_NAME,   
    SET_CONTACT_EMAIL,  
    SET_CONTACT_SUBJECT,
    SET_CONTACT_MESSAGE,
    SEND_CONTACT_INFORMATION,
    SET_CAN_SHOW_CONTACT_MESSAGE,
};